### ISSUE TITLE
Proposed renaming of device identifier API

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/DeviceIdentifier#40]
**Problem description**
Current name of the device identifier API in the basepath is `dvi`. However, as an additional API "IMEI Fraud" has been included in the sub-project ,it is no longer appropriate to name the device identifier API after the sub-project.

**Expected behaviour**
API name in basepath should closer reflect the documentation name. As hyphens are allowed in the basepath name, it is proposed to change this to `device-identifier`.

**Alternative solution**
None proposed

**Additional context**
This new name follows the convention adopted by many other APIs

**Comment by sachinvodafone** [comment]
Hi @eric-murray , It looks fine to me. Thanks
