### ISSUE TITLE
Rename API title to CAMARA Mobile Device Identifier API

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/DeviceIdentifier#46]
**Problem description**
Current API title is "CAMARA Device Identifier API", but the API only applies (and can only apply) to mobile devices. It is proposed to make this clearer by renaming the API to "CAMARA Mobile Device Identifier API"

**Expected action**
Update YAML filename and `title` field within YAML to "CAMARA Mobile Device Identifier API"

**Additional context**
None

**Comment by sachinvodafone** [comment]
It seems fine , if other devices like IoT are excluded.

**Comment by HuubAppelboom** [comment]
I think it is best to add the Mobile in front of it, so it is clear what you can expect
