### ISSUE TITLE
Use API name as file name of the the YAML and with the info.title field.

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/DeviceIdentifier#79]
**Problem description**
The file https://github.com/camaraproject/DeviceIdentifier/blob/main/code/API_definitions/CAMARA%20Mobile%20Device%20Identifier%20API.yaml should be named "device_identifier.yaml"

There does not seem to be a convention on how yaml files are named but the top-active subprojects mostly use something like
apiname_feature.yaml 
No Camara, all lowercase, underscore.

**Expected action**
rename the file

**Additional context**
Sorry, for this nit-picking

**Comment by eric-murray** [comment]
We can update the filename if and when Commonalities specify some rules on file naming. I'd suggest to raise this issue in Commonalities.

**Comment by AxelNennker** [comment]
> We can update the filename if and when Commonalities specify some rules on file naming. I'd suggest to raise this issue in Commonalities.
@eric-murray 
I do not care that much, and actually I am not a big fan of too many rules.

**Comment by hdamker** [comment]
Let me shortly jump in: it is right that there no rule yet for the for the filename, but all API release candidates for the Meta-release are using either `api-name.yaml` or `api_name.yaml`, so here it would be `device-identifier.yaml` or `device_identifier.yaml`. It's maybe a topic for Release Management to define a guideline. 

But practice and my personal preference is that the filename reflects the API name without any additions. Similar for the info.title field (here the API Design Guidelines have at least an example).

I have changed the issue title. Feel free to close with "Close as not planned", as this is currently potentially the least important issue.

**Comment by eric-murray** [comment]
I'm happy to leave this open until a rule is defined.

Personally, I'm a big fan of having spaces in filenames, because it shows up just how many bad programmers there are out there, and forces them to think about their implementation. Why else would Microsoft name a folder `Program Files`.

**Comment by hdamker** [comment]
@eric-murray have created https://github.com/camaraproject/Commonalities/issues/284 for that, as consistency is important here. But fine for device-identifier as it will not be part of this meta-release ;-)
